baseURL = "https://volksentscheid-transparenz.de/"
languageCode = "de-DE"
title = "Volksentscheid Transparenz"
defaultContentLanguage = "de"
enableRobotsTXT = true

[permalinks]
  blog = 'blog/:year/:month/:slug/'

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = 'authors'
weight =  80
  [[related.indices]]
    name = 'date'
    weight = 40
    pattern = 2006
  [[related.indices]]
    name = 'tags'
    weight = 60

[mediaTypes]        
  [mediaTypes."application/atom"]
    suffixes = ["xml"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "atom"
    isPlainText = false
  [outputFormats.Json]
    mediaType = "application/json"
    baseName = "index"

[outputs]
home = ["HTML", "Json"]
section = [ "HTML", "Atom", "Json" ]
